name: AOSP Build

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Setup jdk
      run: | 
             sudo apt-get update
             sudo apt-get install openjdk-11-jdk bison g++-multilib git gperf libxml2-utils make zlib1g-dev zip liblz4-tool libncurses5 libssl-dev bc flex curl
             java -version
             df -h
 
    - name: mkdir folder
      run: |
            mkdir ~/android
            cd ~/android
    - name: Install repo
      run: |
             mkdir ~/bin
             curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
             chmod a+x ~/bin/repo
    
    - name: source
      run: |
            cat > ~/.bashrc << EOF
            export PATH=~/bin:$PATH
            EOF
            source ~/.bashrc
            repo init -u https://github.com/Corvus-R/android_manifest.git -b 11
            repo sync -j$(nproc --all) 
    

    
    - name: Build
      run: |
             source build/envsetup.sh && lunch
             make -j$(nproc)
